### ISSUE TITLE
duplicate key value violates unique constraint "uk_dudttlotp8tbpk3nas8ywkq92"   Detail: Key (book_list_id)=(4) already exists.

### ISSUE THREAD

**Issue by sherwinwater** [sherwinwater/SpringbootEbook#6]
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Aug 22 22:18:59 EDT 2020
There was an unexpected error (type=Internal Server Error, status=500).
**Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_dudttlotp8tbpk3nas8ywkq92"
  Detail: Key (book_list_id)=(4) already exists.**
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:153)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:119)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 132 more
```

**Comment by sherwinwater** [comment]
Database loader Class tries to load the data again to trigger the exception.
