### ISSUE TITLE
error: detached entity passed to persist

### ISSUE THREAD

**Issue by sherwinwater** [sherwinwater/SpringbootEbook#8]
```
Hibernate: insert into role (name, id) values (?, ?)
Hibernate: select nextval ('hibernate_sequence')
Hibernate: insert into role (name, id) values (?, ?)
Hibernate: insert into cart (created_by, creation_date, last_modified_by, last_modified_date, total_price) values (?, ?, ?, ?, ?)
Hibernate: insert into ebook_user (created_by, creation_date, last_modified_by, last_modified_date, activation_code, alias, user_id, email, enabled, first_name, last_name, password) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2020-08-28 13:20:14.951  INFO 3800 --- [  restartedMain] c.s.e.aspect.UserServiceLoggingAspect    : logAfterThrowing running .....
2020-08-28 13:20:14.954 ERROR 3800 --- [  restartedMain] c.s.e.aspect.UserServiceLoggingAspect    : Exception in com.sherwin.ebook.service.UserService.save() with cause = {}

**org.hibernate.PersistentObjectException: detached entity passed to persist: com.sherwin.ebook.domain.Role**
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:120) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:113) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:742) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:710) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.spi.CascadingActions$7.cascade(CascadingActions.java:298) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:492) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:416) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:525) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:456) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:419) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:151) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.cascadeAfterSave(AbstractSaveEventListener.java:459) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:293) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:193) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:123) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:185) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:128) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:718) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:704) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
```

**Comment by sherwinwater** [comment]
@ManyToMany(fetch = FetchType.EAGER)
_//    @ManyToMany(cascade = CascadeType.ALL)  // detached entity passed to persist_, 
    @ToString.Exclude
    @JoinTable(
            name = "users_roles",
            joinColumns = @JoinColumn(name = "user_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "role_id", referencedColumnName = "id")
    )
    private Set<Role> roles = new HashSet<>();
